services:
  - type: worker
    name: berkat-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 main.py"
    envVars:
      - key: BOT_TOKEN
        value: "твой_токен_бота"